### ISSUE TITLE
enterprise requests

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#275]
high priority
 - [x] option to keep pass phrase in memory #197 
 - [x] integrate WKD #314 #296 
 - [x] implement FES integration to pull OrgRules during setup #339 #340  #276 (July 2021)
 - [x] forbid backing up keys #277 (September 2021)
 - [x] prepwork for EKM integration https://github.com/FlowCrypt/flowcrypt-ios/issues/385 (July 2021)
 - [x] implement EKM integration to pull keys during setup  #279 (August 2021)

medium priority
 - [x] disallow attester search https://github.com/FlowCrypt/flowcrypt-ios/issues/299 (September 2021)
 - [x] message signing #274 (September 2021)

lower priority:
 - [x] attachment sending #341 #196  (done)
 - [ ] message signature verification #609 #278 (date unknown)
 - [x] attachment download #193 #341 #194 #195  (done)

later:
 - [ ] #841
 - [ ] handling of large messages #230

**Comment by tomholub** [comment]
superseded by #977
