### ISSUE TITLE
major usability fixes

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#606]
These are issues that frustrate me frequently.

- [x] missing contact suggestions when composing email, searching contacts #283 
- [x] encryption of attachments slow and progress unclear https://github.com/FlowCrypt/flowcrypt-ios/issues/695
- [x] oauth grant friction during setup #531 
- [x] drafts not supported #514 
- [x] (waiting for Google verification of scope) few contacts found #743
- [ ] (in progress) missing conversation view in inbox #608 
- [x] (waiting to merge) decryption of messages with attachments is slow, progress unclear #783 

later:
- have to repeatedly enter pass phrase, should instead use faceid #456

**Comment by tomholub** [comment]
closing, #657 is last remaining issue
