### ISSUE TITLE
priorities - iOS

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#977]
current backlog 
 - [x] (Roma) google grant friction #530 
 - [x] (Ivan) #877 
 - [x] (Ivan) #721 
 - [x] (Ivan) #404

new requests
 - [x] (Roma) security - add signature verification #278 
 - [x] (Roma) forwarding encrypted messages #900 
 - [x] (Roma) forwarding encrypted attachments #903 
 - [x] (Ivan+Mart) Preview attachment contents #902 #1213 #1205
 - [x] (ivan) add and test support on iPads #724 #457
 - [x] send password-protected messages through web portal + password policy #955 #1091 
 - [x] adding cc and bcc on compose screen #954 
 - [x] reply all #953
